name: "trials-ha-addon"
description: "trials-ha-addon"
version: "v2.6.1-alpha"
slug: "trials-ha-addon"
image: ghcr.io/banban525/trials-ha-addon-addon/{arch}
url: https://github.com/banban525/trials-ha-addon
arch:
  - aarch64
  - amd64
init: false
host_network: true
services:
  - mqtt:need
ingress: true
ingress_port: 8098
ports:
  8099/tcp: 8098
ports_description:
  8099/tcp: "Frontend tcp-listen port"
map:
  - path: "/addon_config"
    type: addon_config
    read_only: false
  - path: "/ssl"
    type: ssl
    read_only: true
  - path: "/data"
    type: data
    read_only: false
options:
  mqtt: {}
  echonet: {
    device_ip_list: []
  }
  device_ip_list: []
schema:
  mqtt:
    broker: str?
    option_file: str?
    ca_file: str?
    cert_file: str?
    key_file: str?
    base_topic: str?
  echonet:
    target_network: str?
    device_ip_list:
      - str
    command_timeout: int?
    disable_auto_device_discovery: bool?
    alias_file: str?
    legacy_multi_nic_mode: int?
    unknown_as_error: bool?
  device_ip_list:
    - str

